### ISSUE TITLE
Lots of bears around - organization needed

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1047]
Hey, as the amount of bear grows (I have 5 new bears ready in a PR) we should start thinking about the following issues:

- We'll want to split off bears in groups, probably grouped by language, into own repositories and make them own pypi packages.
- We'll want a naming convention for bears.

Any input would be nice.

**Comment by AbdealiJK** [comment]
I just checked out `conda` it seems as though to use conda the preferred method is by installing `miniconda` - which has python installed also. That is a slight issue because its irritating. It doesnt integrate easily into `python.org`'s python
miniconda does not seem to be in apt-get. Also I cannot find miniconda's code online (not sure if its opensource) but I can find conda.

**Comment by AbdealiJK** [comment]
@sils1297 could you give me edit rights on `coala-bears`

**Comment by AbdealiJK** [comment]
Done \^_^/ https://github.com/coala-analyzer/coala/pull/1566
