### ISSUE TITLE
PHP and Objective-C missing for "doxygen.coalang"

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1143]
The doc-extraction specification does not contain PHP and ObjC, but they are supported from doxygen.

We need just to lookup the doxygen specification and extend our one^^

**Comment by sils1297** [comment]
FWIW this file holds specification for documentation comments, i.e. the task involves looking up common standards for documentation comments and writing them down ther.

**Comment by sils1297** [comment]
Sharing useful information from the discussion:

each doc marker is a set of three values, e.g. a doxygen comment in C is usually

```
/**
 * content...
 * content ...
 */
```

so the start marker is `/**` then we have the middle marker (arbitrarily often) `\ *` (note the escaped space), and then the end marker `\ */`
this bug is about finding out what the usual style for documentation comments is
in PHP and objective C
so our algorithm works with those languages too
