### ISSUE TITLE
Remove bare except clauses

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1219]
I could find 6 statements in source code with bare exception clauses. I think it's better to specify explicitly the type of exception you're catching. In this way you wouldn't catch accidently `KeyboardInterupt` when you intent only to check for `ImportError`, for example.

**Comment by Makman2** [comment]
Could you write down the locations here? Maybe it's intended at some locations^^

**Comment by Uran198** [comment]
Here are the locations:
```
./coalib/output/printers/EspeakPrinter.py:26:        except:  # pragma: no cover
./coalib/bears/Bear.py:96:        except:
./coalib/misc/Constants.py:77:except:  # pragma: no cover
./coalib/settings/FunctionMetadata.py:105:        except:
./coalib/processes/BearRunning.py:105:    except:
./bears/js/JSONFormatBear.py:12:    except:
```
Although I think the better would be to write `except Exception` at the very least. Also there is pep8 recommendation regarding this. It recommends to limit usage of bare clauses to two cases:

1. If the exception handler will be printing out or logging the traceback; at least the user will be aware that an error has occurred.
2. If the code needs to do some cleanup work, but then lets the exception propagate upwards with raise . try...finally can be a better way to handle this case.

**Comment by Makman2** [comment]
I'm more in favor of using plain `except:` since it's not that verbose than `except Exception:`. Also it's important to know that not all exceptions derive from `Exception`,  but from `BaseException`.

In some cases (like in `Bear.py`) I would catch everything, a bear is intended to run inside a thread/subprocess and shall not throw something like a `KeyboardInterrupt`.

So where I would agree with you:
- `Bear.py`: I would keep that, see above
- `Constants.py`: `makedirs()` should be definitely better catched and better error-handled^^
- `FunctionMetadata.py`: Keep that, this class is general-purpose and shall catch every error raised from your custom function, it shall not intervene into program workflow via `KeyboardInterrupt` or else.
- `BearRunning.py`: Not sure, the code does a bit more, need to look at it.
- `JsonFormatBear.py`: There definitely belongs an `except AttributeError:` (I hope that's the correct exception for missing module attributes)

`EspeakPrinter` will be removed sooner or later, so I think that's okay :P

At least that's my opinion, @sils1297 what do you think?

**Comment by Makman2** [comment]
Update on `BearRunning.py`:
This `except` is not even needed, since all exceptions are catched inside `Bear.execute()` itself. It's only needed when someone overrides `Bear.execute()` such that it's not handling errors.
@sils1297 is this intended?

**Comment by sils1297** [comment]
@Makman2 the idea was that if somebody does evil things - like overriding `execute` - we'd still catch the exception and it wouldn't be possible to break the coala process with a bear.

**Comment by Makman2** [comment]
Some of the cases involve some refactors to make it clean, I would say these get fixed on demand when refactoring at the locations anyway^^

See also #975

**Comment by AbdealiJK** [comment]
I was trying to fix this.

I have left the following errors as is:
```
$ git grep -e "except:" -e "except Exception" -e "except BaseException"
coalib/bears/Bear.py:        except:
coalib/coala_json.py:    except BaseException as exception:  # Ignore PyLintBear
coalib/coala_main.py:    except BaseException as exception:  # pylint: disable=bro
coalib/collecting/Collectors.py:                except BaseException as exception:
coalib/output/ConsoleInteraction.py:    except Exception as exception:  # pylint: 
coalib/output/dbus/DbusDocument.py:        except BaseException as exception:  # p
coalib/processes/BearRunning.py:    except:
coalib/processes/Processing.py:        except Exception as ex:
coalib/settings/FunctionMetadata.py:        except:
```
Reasons:
Bear & BearRunner - User written bears are outside our control so we want to catch them
coala_json, coala_main, DbusDocument - Throw nice error message if anything bad happens
Collectors - Catch errors when trying to import a bear (again they can do anything)
ConsoleInteraction, Processing - Errors when applying an action
FunctionMetadata - @Makman2 told to keep it :P (I still do not know what it does)
