### ISSUE TITLE
License file should not have execuable permission

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1327]
Our LICENSE file seems to be executable. Is that required ?

```
ajk@ajk-ThinkPad-R60:~/Documents/coala/coala$ ls -l LIC*
-rwxrwxr-x 1 ajk ajk 34520 Dec 20 12:16 LICENSE
```

**Comment by yash14123** [comment]
Can you give me a hint as to how to go about fixing this?

**Comment by AbdealiJK** [comment]
@yash14123 I'm not sure if @sils1297 has a reason for whether it should be executable (maybe the general norm is to have an executable LICENSE file ?)
So, let's wait for him to check if this is wanted or not.

But answering your question, to be able to fix this you'd have to use `chmod` to change he  file's mode bits.
Something like `chmod -x LICENSE`
More info here - https://www.mkssoftware.com/docs/man1/chmod.1.asp

**Comment by Makman2** [comment]
@AbdealiJK don't think so we need an executable LICENSE file, just because it doesn't contain some valid code or whatever. Since the LICENSE file is automatically added by github when creating a repository this could be the cause^^
@yash14123 Like @AbdealiJK said, change the file mode and remove the executable flag. git let's you stash this change so you can commit that.

**Comment by yash14123** [comment]
Please assign me this task @Makman2 . 
Thanks. :)
