### ISSUE TITLE
CI scripts: Use package.json to install npm dependencies

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1351]
and ask @AbdealiJK for further questions on this one :)

**Comment by AbdealiJK** [comment]
The issue basically involves using `npm install -g` to install a list of npm packages instead of doing something like `npm install -f <pkg1> <pkg2> <pkg3>`.

We already created a package.json file earlier and now, we just have to make our continuous integration systems use it. We have 2 continuous integrations: `appveyor`, `travis`, `circleci`.

Currently only `circleci` uses npm packages. It can be found in `.misc/deps.sh`

**Comment by AbdealiJK** [comment]
Also, it'd be good to install npm deps locally and add the node_modules to the ~/.circleci

We can then cache this node_modules to increase speed
