### ISSUE TITLE
coalib/coala_delete_orig.py - Better message when deleting file

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1360]
Currently, we say "Deleting file" which sounds scary.

We would like to say "Deleting old backup file"

**Comment by iamshubh22** [comment]
@AbdealiJK I would fix this.

**Comment by AbdealiJK** [comment]
@Makman2 @sils1297 could you add him to the org so that he can assign himself ?

**Comment by sils1297** [comment]
@iamshubh22 cool, please do both issues (this and https://github.com/coala-analyzer/coala/issues/1359) in different commits, ideally in the same PR because they are related. (Otherwise you'll get conflicts.)

Also note that we'd love it if you don't solve more than two newcomer issues because they are really hard to come up with and we still need some for other contributors.
