### ISSUE TITLE
coalaTest.py: Remove `sys.version_info` check

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1418]
```python
if sys.version_info < (3, 4):
    import imp as importlib
else:
    import importlib
```
These lines shouldn't be needed. 

https://docs.python.org/3/library/importlib.html
> 31.5. importlib – The implementation of import
>
> New in version 3.1.

**Comment by tushar-rishav** [comment]
@Makman2  Probably, we are using `importlib` to reload the modules under `execute_coala` which now have been moved to `coalib/tests/TestUtilities`.  Beside, @AbdealiJK  suggested to remove the `reload` too and further test with travis. One more thing, we are supporting Python versions >= 3 right? So that check might not be required.

**Comment by Makman2** [comment]
@tushar-rishav Yeah right :)
