### ISSUE TITLE
Lint: Add helper to autogenerate configuration files

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1475]
some linters need config files and it would be nice if the lint class could autogenerate them for you somehow so I just need to give the content somewhere or can generate it from settings.

**Comment by AbdealiJK** [comment]
I was thinking something like `setup.cfg` would be nice.

for example we do:
```
[pylint:MESSGE CHECK]
disable=all
```
And this takes all the pylint sections and makes a config ?

**Comment by AbdealiJK** [comment]
Needs more info.

Are we looking at something like `setup.cfg` where I can set `pytest` and `coverage` configs also ?
Or are we looking at something like we have a section for a bear and use those to set their config file ?

I'd prefer the first, because I do not want to parse the configs and rewrite then with different names.
Also, a config file for pylint has multiple sections of it's own. How would we handle that ?

**Comment by sils1297** [comment]
We don't want to make the configuration of coala more complicated. Bears should never parse their own config. Example:

Checkstyle needs an XML based config that tells it about line length and stuff. We already have common names for settings, e.g. max_line_length. We now want the CheckstyleBear to generate such an XML config so Checkstyle uses the same line length setting as all other bears too.

No cfg files involved. We can make a parser for cfg files so people can configure coala with that instead of coafiles but that'd be quite another issue.

**Comment by AbdealiJK** [comment]
@sils1297 Ah. got it. This file that Lint would generate will be temporary - correct ?

**Comment by sils1297** [comment]
Yes
