### ISSUE TITLE
CI: Increase Appveyor timeout

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1500]

**Comment by sils1297** [comment]
@AbdealiJK is the timeout increase sufficient or is there something else behind this?

**Comment by AbdealiJK** [comment]
The time out currently is 35 seconds. I highly doubt it is that.
Though, the failure always happens in coalaTest which is our slowest test because it parses through the whole project.
I think with @tushar-rishav 's commit which fixes that (he runs coala on a tempfile, not on the whole project) this **may** get fixed

**Comment by tushar-rishav** [comment]
@AbdealiJK @silk1213    Yeah it should be fixed now. I am using `prepare_file` now in `coalaTest`.

**Comment by AbdealiJK** [comment]
Closing this as it has not happened for a long time.

It seems the reason was simply that coala integration tests were too slow.
