### ISSUE TITLE
bug: Something wrong with handling brackets

### ISSUE THREAD

**Issue by nishant-mor** [coala-analyzer/coala#1613]
![screenshot from 2016-02-18 21-20-21](https://cloud.githubusercontent.com/assets/11739327/13195698/be599da2-d7de-11e5-86ca-37ccdc563447.png)
![screenshot from 2016-02-18 21-31-10](https://cloud.githubusercontent.com/assets/11739327/13195697/be5510de-d7de-11e5-845c-3505660b1659.png)

**Comment by Makman2** [comment]
@nishant-mor Maybe it's the globs. Can you try using `coalib.parsing.Globbing.glob` manually inside the python interpreter using the same path and look what it yields?
And also an `ls` on this folder would be nice to see if something's missing^^

**Comment by nishant-mor** [comment]
ls of parsing folder ?

**Comment by Makman2** [comment]
no directly inside  `.../New folder (3)/coala`

**Comment by nishant-mor** [comment]
@Makman2 see the 2nd screenshot it is ls of coala folder

**Comment by Makman2** [comment]
huh interesting it wasn't displayed for me before :O sorry :/

**Comment by AbdealiJK** [comment]
The brackets must be the problem

**Comment by nishant-mor** [comment]
@AbdealiJK yeah i removed the brackets and it worked, any idea how to fix this

**Comment by AbdealiJK** [comment]
@Makman2 has made most of the escaping stuff - he'd know better.
But it's somewhere there I'm guessing
(Either that or globbing)

**Comment by Makman2** [comment]
Thats @fneu 's address, hes the master globber :)

**Comment by fneu** [comment]
It's not a bug, it's a **feature**!

No, I'm actually serious on this. Citing Glob Syntax from Docstring:
"""
    Glob Syntax:
    '[seq]':         Matches any character in seq. Cannot be empty.
                     Any special character looses its special meaning in a set.
   '[!seq]':         Matches any character not in seq. Cannot be empty
                     Any special character looses its special meaning in a set.
    '(seq_a|seq_b)': Matches either sequence_a or sequence_b as a whole.
                     More than two or just one sequence can be given.
    '?':             Matches any single character.
    '*':             Matches everything but os.sep.
    '**':            Matches everything.
"""

So the brackets are the problem: `(3)` get's interpreted as a **choice** of only three. When evaluating all the choices, the brackets get removed of course. Hence the folder name with the brackets is not matched any more.

The idea behind that was to allow `**/*.(c|h|py)` for file endings and such - obviously the brackets must be removed in that case.

work around: use backslashes to escape the brackets (and PLEASE tell me `\(3\)` is working for your case ^^)

anyways, I'm open to discussion of how we handle this, since we have not released a 1.0 I am fine with breaking user interaction *if there are good reasons for this*.

**Comment by sils1297** [comment]
@fneu this is definitely a bug, we have no brackets in the glob we provide, we do an abspath which introduces the brackets so coala is responsible for escaping that!

**Comment by fneu** [comment]
@sils1297 Ok I get you. We need a `glob_abspath` to handle parentheses (not brackets btw.) and we need to use that wherever we extend relative globs to absolute globs.

Which is best done in Globbing.

Which means we shouldn't touch globs outside of Globbing.

Which means we will fuck this up when we want a glob to be relative to some path from a setting. Maybe. Anyways. I'm going to fix this.

**Comment by sils1297** [comment]
we'd rather need an "escaped abspath" or so, so if we have a glob like `*.(c|h)` in `/home/fneu/coala (test)/` and we do this escaped_abspath('*.(c|h)')` we should get `/home/fneu/coala \(test\)/*.(c|h)`, i.e. the first set of brackets escaped, the second not

**Comment by fneu** [comment]
@sils1297 we mean the same. It's not very straight forward though

**Comment by fneu** [comment]
ok, so proper way is to add a functions to Globbing to allow to properly join a glob and a path.

`os.path.abspath` destroys the glob under certain circumstances
`os.path.join` doesn't escape parentheses

**Comment by hypothesist** [comment]
Matching `*.(c|cpp)` is necessary, so we can't change that. That leaves us with the option to include `*.(c|cpp)` as a file by itself - that is check for files with ".(c|cpp)" ending (I mean literally, not C or C++ files: a (c|cpp) file). That is the only way I can see where `.../New folder (1)/...` is not interpreted as `.../New folder 1/...` (which is what is happening currently)
@sils1297 @fneu @AbdealiJK

**Comment by sils1297** [comment]
I don't understand what you want, what's wrong with not doing an abspath on paths or making an own abspath routine?

**Comment by hypothesist** [comment]
Currently, when you pass `.../New folder (1)/...` to `iglob(pattern)` the result is `.../New folder 1/...`

That is an expected output though, since `main.(c|cpp)` should output `['main.c', 'main.cpp']`

My proposal is let `main.(c|cpp)` output `['main.c', 'main.cpp', 'main.(c|cpp)']`. This way that feature doesn't break, yet `.../New folder (1)/...` gives `['.../New folder (1)/...', '.../New folder 1/...'` of which only `.../New folder (1)/...` will pass.

**Comment by fneu** [comment]
@hypothesist that really is an interesting approach that could actually work for most cases.

That said, you could probably call it cheating or at least it is neither elegant nor simple for an usability approach.

I am still in favor of doing this 'right' and sticking to the syntax we currently advertise. No surprises. `'(A|B)`' will evaluate to `'A', 'B'` and `'(3)'`will evaluate to `'3'`.

This is the way globs work currently and I like it unless we drop the `(either|or)` syntax altogether.


The problem here is not about glob evaluation, but glob creation. We take the coala root directory from the setting and `os.path.join()` it with a glob expression that looks for bears. This way we find our bears independent of the current directory(`os.getcwd()`) and on every system.

This works as long as there are no parentheses in the path name from the settings that we add to the glob. This path was never intended to be a glob expression.

We therefore cannot use `os.path.join()` and need another method in `Globbing.py` that allows joining a path and a glob. This method must escape the path properly before calling `os.path.join`.


This way we keep our syntax (and require people to escape parentheses they need in their globs) and we avoid the automatic creation of invalid globs as is currently the case (in certain git/install directories of coala)

**Comment by hypothesist** [comment]
@fneu Hmm, yes. That is a much better approach. Okay, I'll work on this. (But I have completed the temporary hack too, if you want a quick-fix.)

**Comment by AbdealiJK** [comment]
Marking for 0.5.0 as it blocks https://github.com/coala-analyzer/coala/issues/1831 which is needed for the 0.5.0 release.
