### ISSUE TITLE
Maintaining cross-compatability with coala-bears

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1683]
We have the problem to test changes in `coala` inside `coala-bears`, since it uses modules from `coala`.

I would propose following maintainance strategy:
1. The requirements file for `coala-bears` gets a version **range** for coala, see http://stackoverflow.com/questions/8795617/how-to-pip-install-a-package-with-min-and-max-version-range.
2. Changes inside `coala` are made independent from `coala-bears` from that time on.
3. After each commit in `coala` or regularly (makes more sense since we merge quite often) we adjust the maximum version range in `coala-bears`. If `coala-bears` breaks, changes need committed that fix `coala-bears` together with raising the minimum version number to the coala version the fixes adapt to.

**Comment by sils1297** [comment]
I don't see the benefit of the range tbh

**Comment by Redridge** [comment]
Couldn't it be a specific version. Especially one that doesn't break the bears?

**Comment by sils1297** [comment]
e.g. it might break in between the range

**Comment by Makman2** [comment]
it can't break inside the range since the range is fixed^^

**Comment by Makman2** [comment]
I'm more in favor of using ranges since not only a single version of coala has to be supported by coala-bears, the maintenance overhead is the same like specifying an exact version. So this is a compromise of our current requirements that use `>=`.

**Comment by AbdealiJK** [comment]
I also think that a range is pretty much the same as `==` (with minimal benefits)
I think that once we have a stable release of `coala` this won't be an issue anymore.

Currently we have `coala >= 0.4.1.dev20160219113548` in `coala-bears`. So, when `pip` checks for `>=` it finds newer versions and uses the latest dev release. BUT if we release `0.5.0` pip will search for versions above `0.4.1.dev20160219113548` and come across a nice stable version of `0.5.0` and wouldn't go above that. It would just install `0.5.0`

Next, when we release `0.5.0.devxxx` coala-bears's CI will still use `0.5.0` as that's the stable version (and we aren't using `--pre`). Hence, this `coala-bears` won't be affected by any major thing in `coala`.

So, next time we release `0.6.0`,` things in `coala-bears` will break (which is completely fine) and needs to be fixed in `coala-bears` (similar to how the person incrementing the version in `==` would) and then the next release of `coala-bears` should be done.

I mean, imaging another library like `setuptools` updating ... and if they do something that breaks backward compatibility - we'd fix it only when they release their stable version (that breaks stuff). Similar scenario

**Comment by AbdealiJK** [comment]
@sils1297 mentioned we can allow `~=0.4.x` *and* `==0.4.x.dev9999` in coalabears.
Which makes sense too !

https://github.com/coala-analyzer/coala/commit/f11570b3a6bfc8c3c04aa761861881566de32476#commitcomment-16666810

**Comment by AbdealiJK** [comment]
Closing this.
https://github.com/coala-analyzer/coala/issues/1852 seems to have concluded on the method to do this
