### ISSUE TITLE
gives_corrected should only give output when results output is not empty.

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1705]
This is for the `Lint` class. If no result output is there, then the resulting diff in `Result` tries to remove the line, because there's nothing to add. There should be a check to ensure that there is some result before yielding the result.

**Comment by AbdealiJK** [comment]
I didn't follow. So, if you have a `gives_corrected`, I'm guessing `stdout` gives the corrected file you give to `stdin`. If the stdout == stdin, we dont do anything, as the linter didn't change the file in anyway.

Does your linter give out **nothing** if the file was correct ? And the fixed file if the file had some problem ?

**Comment by SanketDG** [comment]
@AbdealiJK The linter gives out nothing if the file is incorrect, it gives out everything on `stderr`. If the file is correct, it gives out output on `stdout`

Narrowing it down, this is where the results are yielded if `gives_corrected = True`

```python
def _process_corrected(self, output, filename, file):
    for diff in self.__yield_diffs(file, output):
        yield Result(self,
                     self.diff_message,
                     affected_code=(diff.range(filename),),
                     diffs={filename: diff},
                     severity=self.diff_severity)
```

Now if I have nothing on `stdout` or `stderr` for that matter, results still get yielded.

**Comment by AbdealiJK** [comment]
This seems to be something Lint cannot handle currently.
I think the best way to do it right now would be to override Lint._process_corrected and check this and then call `Lint._process_corrected(self, ..)`.
I've never seen this behaviour before and it seems like a one off thing. If we find other linters having this same issue we can add it to lint later ?

The reason I'm against adding it to Lint by default is because the output can be empty sometimes.
For example: Think of a StripCommentsBear which needs to remove comments and it comes across `__init__.py` - here the result could be empty. 

@Makman2 is revamping the Lint class considerably which will potentially make this easier too - so, lets not do this right now ?

**Comment by SanketDG** [comment]
> The reason I'm against adding it to Lint by default is because the output can be empty sometimes.
> For example: Think of a StripCommentsBear which needs to remove comments and it comes across __init__.py - here the result could be empty.

Uh yes, that makes sense. Then this is not possible.

> @Makman2 is revamping the Lint class considerably which will potentially make this easier too - so, lets not do this right now ?

Okay.

**Comment by AbdealiJK** [comment]
Closing this issue as wont fix
