### ISSUE TITLE
docs/User/install.rst: Minor changes

### ISSUE THREAD

**Issue by srisankethu** [coala-analyzer/coala#1786]
In the note section after Alternate Installation:

1. change pip -> pip3
2. highlight command properly

![screenshot from 2016-03-02 18 38 45](https://cloud.githubusercontent.com/assets/12644108/13461161/eccc3e36-e0a5-11e5-89df-fb4a9221cabc.png)

difficulity/newcomer

**Comment by saurabhiiit** [comment]
@srisankethu Can you assign me this?

**Comment by srisankethu** [comment]
Ask @AbdealiJK to assign this issue to you. It seems you aren't assigned to any issues right now, so I think you can  do this

**Comment by AbdealiJK** [comment]
@saurabhiiit You've done more than 2 newcomer issues. Could you leave newcomer issues to newcomers and start doing `difficulty/low` or higher issues from now on ?
We prefer if a person doesnt do more than 2 newcomer issues so that other newcomers get a chance too !

You're completely ready to tackle more difficult issues :)

**Comment by saurabhiiit** [comment]
@AbdealiJK I have done only commit of newcomer which I finished 5 minutes back

**Comment by AbdealiJK** [comment]
Ouh, alright then - my mistake (Thought I saw your name multiple times)

Assigning this to you @saurabhiiit

**Comment by saurabhiiit** [comment]
@AbdealiJK Thank you
