### ISSUE TITLE
coalang-facility: Get rid of `language_family`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1811]
Providing the language only identifies a programming language completely, there's no need for having `language_family`.

**Comment by charizard42** [comment]
i want to work on this

**Comment by abhsag24** [comment]
@Charizard42 still on it?

**Comment by charizard42** [comment]
@abhsag24 you can have it. i am working on gitmate

**Comment by abhsag24** [comment]
so basically all that is needed to be done is to remove `language_family` from `LanguageDefinition` and break up all existing `coalang` files into files with different languages? @Makman2  please confirm.

If this is the case I believe this would increase redundancy since we'd loose the `Default` section and inheritable settings, which are common for all languages in the `language_family`,  would we want this? 
If we don't want that, then i guess we need a clear vision on how we want our coalang files for `LanguageDefinition` to look like, in which case this issue needs design?

**Comment by Makman2** [comment]
See also https://github.com/coala-analyzer/coala/issues/1898 .
So if possible it would be nice to break up languages into different files each, but the concept design is not that easy^^ I'm not sure how we want to implement that specifically^^
We maybe need to use JSON if this adheres some advantage^^
