### ISSUE TITLE
Use InvalidLinkBear in docs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1812]
Add InvalidLinkBear in the docs. Maybe in a disabled section ?
so that issues like https://github.com/coala-analyzer/coala/issues/1782 can be avoided

**Comment by Adrianzatreanu** [comment]
do we want to avoid situations like that? they are newcomer issues :p

**Comment by sils1297** [comment]
I think we want to avoid not working links because they are bad. You can
live with typos but links that don't work... if it's a redirect that's
another story.

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-06 23:27 GMT+01:00 Zatreanu Adrian-Gabriel <notifications@github.com
