### ISSUE TITLE
Add docs for coalang

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1816]
coalang seems to be becoming more and more popular right now.
We have 2 issues blocked by it and it will probably become popular as we've depleted the list of linter based bears we want.

We should document it properly (once it actually stabilizes to some extent). I find lots of questions coming up about it in gitter.

@abhsag24 @hypothesist would love to know whether you think coalang is stable enough for this. If you think it's not, we should add the blocked label to this issue for now until its stable enough.

**Comment by hypothesist** [comment]
@AbdealiJK Currently there are zero bears using coalang. So it's in a very volatile stage, I'd say (there is an open issue to change the whole structure, I just made a PR to change from spaces to underscores everywhere, ...). I think we should wait just a bit more before putting it in the official docs since it may change frequently.

**Comment by abhsag24** [comment]
@AbdealiJK we do package it now, bear writers may go ahead and use it without the documentation anyway , i say we document it, but advise the bear writer that this is subject to change

**Comment by sils1297** [comment]
Agreed

**Comment by AbdealiJK** [comment]
Unblocking it then

**Comment by Makman2** [comment]
At least my doc-extraction stuff works very good, there won't change much inside the current stuff.

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#51
