### ISSUE TITLE
Add += operator in config files

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1819]
so right now sections inherit settings from the "Default" section but only have the option to overwrite them, it'd be cool to have a `+=` operator to append to these settings rather than overwriting them

**Comment by AbdealiJK** [comment]
I was thinking about this, and it seems to be more complicated than I thought.
It may not be worth it.

If this is done:
 - When we do `coala -f file.html` the file.html will be added to all the sections that use `+=`
 - It may be difficult to get ConfWriter to support this smartly. Because it wouldn't know when to use `+=` and when to use `=`. We may just want confwriter to dumbly use `=` everywhere.
 - When we do `coala -f file.html --save` with an existing coafile, and ConfWriter uses `=` would add the file to all the sections where += is there
 - Do we want custom handling for dicts ? If we just do a simple `a + b` in the ConfParser, It gets complicated as dicts do not support addition.
 - String vs List: What if we declare a string in Default and later want to add to the string. Should the next value be added like strings or like lists ?

**Comment by sils1297** [comment]
IMO it's important that a coafile always and only deals with strings. They may be interpreted in the end.

 Settings from CLI should always use =.

One huge concept this would introduce is that settings may actually rely on the order of definition.

**Comment by Makman2** [comment]
Thinking like @sils1297.
For me the need has never arisen to use `+=` on a setting btw^^

**Comment by AbdealiJK** [comment]
@Makman2 @sils1297 FYI this came up in the case of C/C++ in coalang
where a LOT of keywords are common, but things like `try` are not in C but are there in C++

It's repetitive to add the same keywords for C, C++, C#, Objective-C
Also similar for ruby1.x ruby 2.x
Python 2.x, Jython, Python 3.x, etc etc etc

**Comment by sils1297** [comment]
I totally see the usecase, but it defies the nature of a configuration file being static.

**Comment by sils1297** [comment]
marking as wontfix, if somebody wants to take this forward it needs a lot of discussion and design, currently there's no time for that

**Comment by sils** [comment]
actually this will get picked up by coala.io/cep5 !
