### ISSUE TITLE
Add option to run coala while ignoring the coafile

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1838]

**Comment by Makman2** [comment]
Yes we definitely need that :+1:

**Comment by Makman2** [comment]
Though the question is how to implement that:
- Don't use the coafile when providing cli-arguments? (except when providing `--save`)
- Use an extra flag for disabling default coafile?
- Misuse the existing `-c` flag to accomplish this? Something like `-c=devnull`?

**Comment by AbdealiJK** [comment]
I normally do `-c /dev/null` and it works fine :)
Windows can use `-c NULL` and it should work fine I guess ?

@Makman2 your first option will break all editor plugins. And you wouldnt be able to do `-S autoapply=false` temporarily. Nor will you be able to do `-S editor=subl` and so on ... I dont think that's a good solution

I think we can mention that if you give no argument with `-c` (i.e. you do not provide a config file path but use the `-c` arg) it uses no coafile.

**Comment by Makman2** [comment]
Windows works with `-c nul`.

Passing no argument to `-c` is complicated since the arg-parser can't distinguish then between a given section or config file:
`-c section`
could be interpreted as `-c` use no config and execute section `section`, or use `section` as path to the config. Since `-c /dev/null` and `-c nul` work fine, maybe we should just mention this inside docs?
Less code to maintain, same functionality :+1:

**Comment by sils1297** [comment]
well a `--noconfig` shortcut for `-c nul` and `-c /dev/null` would be certainly useful for users because it's not really obvious how to do that for some

**Comment by Makman2** [comment]
totally forgot I proposed that too... yeah `--noconfig` is good :+1:

**Comment by AbdealiJK** [comment]
Right, empty -c would be confusing. :+1: for --noconfig
