### ISSUE TITLE
Console output: Add syntax highlighting

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#1925]
[Python prompt toolkit](http://python-prompt-toolkit.readthedocs.org/en/latest/pages/building_prompts.html#syntax-highlighting) can be used for better syntax highlighting. 

This is also a part of my GSoC proposal.

**Comment by Makman2** [comment]
cool
though we highlight the text from results with red and green showing the problem.

**Comment by sils1297** [comment]
it'd be nice to do our highlighting with a slight background change and the
syntax highlighting with the actual text colour

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-19 16:36 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
good idea :+1:

**Comment by sils1297** [comment]
Alright this task is defined, the goal is to add syntax highlighting to the output with foreground colours and highlight things like additions/removals in the diff and which ranges belong to the result with background colours.

I think this isn't really trivial because of the dual highlighting and the fact that we don't have the info on which language we show there at the moment which is probably needed.

**Comment by mr-karan** [comment]
Since my proposal got accepted, I would like to assign this to myself.
