### ISSUE TITLE
parse_cli: Redundancy in collecting arg list

### ISSUE THREAD

**Issue by tushar-rishav** [coala-analyzer/coala#2170]
We collect the command line args first in [ConfigurationGathering](https://github.com/coala-analyzer/coala/blob/master/coalib/settings/ConfigurationGathering.py#L306) and then again in [CliParsing](https://github.com/coala-analyzer/coala/blob/master/coalib/parsing/CliParsing.py#L40). I am confused here. Since `parse_cli` receives  argument list from ConfigGathering, why do we need to collect args from `sys.argv` rather than just using the received `arg_list` ?
CC @AbdealiJK

**Comment by Hydro8182** [comment]
Hey, I'd like to work on this.

Just to clarify: Is the suggestion to just remove line 40 from CliParsing.py?

**Comment by sils1297** [comment]
@Hydro8182 I don't know, it's unlikely to be that simple. @tushar-rishav is probaly rather likely to help you if you need any assistance.

**Comment by tushar-rishav** [comment]
@sils1297 I think it can be done by just removing the L40. Since @AbdealiJK wrote that line, I think we should also get his view on this.

**Comment by AbdealiJK** [comment]
Uhm, Based on the diffs I see in my commits, I just did some cleaning up in that area, and the sys.argv were always there.

I just checked it out though - In [get_filtered_bears()](https://github.com/coala-analyzer/coala/blob/f9e46c89794035d4dad7dc2a149faf935c28a8c4/coalib/settings/ConfigurationGathering.py#L294) we call `load_configuration()` with arg_list=None, which calls `parse_cli()` with arg_list=None. The behavior of that would change if the L40 is removed.
We use `get_filtered_bears()` for show_bears and stuff. - [coala.py](https://github.com/coala-analyzer/coala/blob/23fd9b988b0e4c74152b9d71ded2696d266d65e9/coalib/coala.py#L38)

So, it does affect **some** branch in the code and it can be None sometime.

Now, if you remove L40 and sys.argv is not read here, when a user does `coala --bear-dirs /path/to/my/bears --show-bears` the bears in /path/to/my/bears will not be shown. Because, the cli_parsing will not know that it needs to search that path (as the sys.argv was never used by it). I believe we want it to be shown - correct ?

So, yeah. I don't think this should be removed.


@Hydro8182 could you check if my logic is right ?
If it is, then please ensure that there is a unittest that tests this.

**Comment by Hydro8182** [comment]
Sorry for the late reply, I just got home. 

I will check it out tomorrow.

**Comment by Hydro8182** [comment]
@AbdealiJK You're right parse_cli is sometimes called without and arg_list. Your --show-bears example still works correctly though, even if the line is removed. That's because a bit farther down argparser.parse_args() - which uses sys.argv when arg_list is None - is used to iterate over the arguments.

So to me it seems like removing the line doesn't change the behaviour of the function.

**Comment by AbdealiJK** [comment]
That's nice :)
Let's remove it then
