### ISSUE TITLE
RubySmellBear doesn't work

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2181]
Run the bear on the example on https://github.com/troessner/reek#example and you'll get an exception.

**Comment by sils1297** [comment]
that's actually an issue in coala-bears btw.

**Comment by Uran198** [comment]
It seems that the issue is that resulting json doesn't have name attribute. From the source [code](https://github.com/troessner/reek/blob/master/lib/reek/report/report.rb#L140-L145) of reek it seems that json format should reassemble yaml, which has [docs](https://github.com/troessner/reek/blob/master/docs/YAML-Reports.md). They might be outdated, though, because running on the example I don't really get the same structure.

**Comment by sils1297** [comment]
@Uran198 are you working on this? It's important, otherwise I'd have to take it up. Need it tomorrowish.

**Comment by Uran198** [comment]
@sils1297 You should take this, I'm having troubles managing my time lately.

**Comment by sils1297** [comment]
@Uran198 did you find anything more?

**Comment by Uran198** [comment]
No, I think you should either ask them about the format or look up the code.
