### ISSUE TITLE
Suggest usage of `git push --force-with-lease` instead of `git push -f` in rebasing tutorials

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2250]
area/documentation

**Comment by sils1297** [comment]
I'm not fully sure about that because you have to explain more to new people.

**Comment by Makman2** [comment]
I'm against this as I agree with @sils1297 , the command looks like it needs more explanation because of the "remote-tip-need-to-be-equal" protection, with our review system there is in principle no possibility to merge such malicious branches (master is protected by GitHub, notification in PR that branch is out-of-date, rultor refuses merge). Our workflow is also more like "that is definitely your branch" and no-one would touch it (unless there are special exceptions if someone wants to take over directly etc, though in fact there's no need for such arrangements).

**Comment by underyx** [comment]
Can't really refute all that, but just to reply to this one point:

>Our workflow is also more like "that is definitely your branch"

I've deleted my own commit before with a force push when I forgot I had already changed something with the github.com editor :D

**Comment by Makman2** [comment]
don't do so :3

**Comment by sils1297** [comment]
so what do we do? I'm currently leaning towards the simpler solution. Might also be because I'm lazy and I'm in issue closing mood though :P

**Comment by Makman2** [comment]
maybe we can mention inside a note "if you want more protective behaviour, you can also use `--force-with-lease`" or so^^

**Comment by sils1297** [comment]
I like adding a note!

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#38
