### ISSUE TITLE
Diff: Needs a function `delete_lines`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2619]
For convenience usage, so you don't need to wrap `delete_line` inside a loop removing each line in your range.

**Comment by hypothesist** [comment]
@micrictor Thanks for working on this issue :)

Could you please drop by at [our gitter channel](https://gitter.im/coala-analyzer/coala) and say hello so that we can invite you to the organization? (This is so that we can assign you this issue - which helps prevent two people working on the same thing unknowingly)

**Comment by sils1297** [comment]
I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

Cheers!

**Comment by Makman2** [comment]
Implemented.
