### ISSUE TITLE
Please add an example how to use Coala

### ISSUE THREAD

**Issue by kimkulling** [coala-analyzer/coala#262]
I am missing an example how to use coala!

**Comment by sils1297** [comment]
related to #136 , I'll try to add an example soon. Thanks for reporting.

**Comment by sils1297** [comment]
@kimkulling I wrote a tutorial for you. It's on #264 . I'd be happy to know if it suits your needs. It should cover all important usecases for coala.

Please note that coala currently only works on linux and mac. We're working on windows support but MS' teeth are sharp and its not on our priority list since nobody uses it for real work.

**Comment by sils1297** [comment]
revised version of the tutorial lies on #273

**Comment by sils1297** [comment]
merged into master. Please reopen or file new issues if anything seems wrong.
