### ISSUE TITLE
coala runs the code of all the bears when started

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2684]
This means importing 6342587165871685 third party modules, which

- can take tons of time
- can have side effects
- can lead to version conflict errors

**Comment by AbdealiJK** [comment]
I'm sorry - I'm confused.
Where do we load all the bears on startup ?
I do not think this is the case, because I can run PEP8Bear successfully without even installing the dependencies of other bears. Similarly, I've had python syntax errors in bears that have not throws errors as I've not used them when running coala.

**Comment by sils1297** [comment]
ah actually we don't - but even loading some will trigger the requirements
resolution of all of them because the import apparently triggers setuptools
to do that for the whole *package* which is coala-bears and thus resolves
*all* dependencies. I think this can be closed as it'll be solved by cib.

**Comment by AbdealiJK** [comment]
Yep, that's because of the setuptools - so, I guess closing this.
@underyx if that was not the issue you were trying to address please reopen, closing it for now.

**Comment by sils1297** [comment]
it was the issue :) thanks
