### ISSUE TITLE
auto-apply for specific bears

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#289]
would be very useful for e.g. correcting spacing in lage projects.

**Comment by sils1297** [comment]
I'm just thinking about how we could do that. We could implement subsections, making our sections even more complicated (e.g. default.SpaceConsistencyBear.action = OpenEditorAction) or so...

**Comment by AbdealiJK** [comment]
I think it makes much more sense to use a nice pre existing config file handler for these things.
IIRC, the reason we made our own Config handler rather than python's was because it didnt exist in python 3.2 .... maybe we want to look into the config file again ?

May want to look into other things like yaml etc also - which would give nice(r?) indentation blocks and allow these in a intuitive block format (like how python indentations are prettier than C `{}`)

**Comment by sils1297** [comment]
> IIRC, the reason we made our own Config handler rather than python's was because it didnt exist in python 3.2 .... maybe we want to look into the config file again ?

That's some refactoring, I currently don't have time for this and our config parser works fairly well right now. We can add a yaml/json/editorconfig/whatever parser easily btw., however we're currently not really supporting recursive structures, just sections, keys and values. @AbdealiJK if you have thoughts about new parsers, please open a new bug.

The way forward for this bug is IMO to simply use our dictionary conversion or something like that. Like:

```
[default]
bears = SpaceConsistencyBear
default_actions = SpaceConsistencyBear: ApplyPatchAction
```

That would be fairly simple.

**Comment by sils1297** [comment]
@Makman2 Interesses? Getting more and more demands for this.
