### ISSUE TITLE
Console text wrapping when window is too small

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#295]
If the terminal window is too small, the text gets wrapped.
Maybe extend the console outputter to handle this case.

**Comment by sils1297** [comment]
Not so easy to do the right way, you should know from CE3D. I've marked all windows bugs with wontfix for now but if we're doing this for unix only there's no way back.

I'm happy to accept proposals on how to solve this.

**Comment by Makman2** [comment]
That's not for windows, that's for all platforms.
In Linux the terminal can also be too small.

**Comment by Makman2** [comment]
And a possible solution: Wrap the console outputter internally inside an outputter that organizes text in your column that you print everytime and text messages right of the table (and the special case when you fill a line number inside the table).

**Comment by sils1297** [comment]
Exactly but getting the width of the terminal is the problem.

**Comment by Makman2** [comment]
Ah okay. I try to look for a way to do that in python.

**Comment by sils1297** [comment]
Something like this:
https://gist.github.com/jtriley/1108174

2015-02-18 16:38 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by fneu** [comment]
I'm not sure this is worth the added complexity. Diffs, filenames and so on will be hard to read anyways, the only thing we could sanely wrap is stuff like actions/questions and so on, right?

How should this look? better than just letting the terminal wrap it anyways? 

Please give me an example of what kind of output you have in mind. Otherwise I'd vote for closing this.

**Comment by sils1297** [comment]
nothing important but a lot of work, not on the roadmap

**Comment by Makman2** [comment]
yeah right that's maybe something pyprint could take care of^^
