### ISSUE TITLE
Git 101 spelling, clarity etc

### ISSUE THREAD

**Issue by sims1253** [coala-analyzer/coala#344]
No errors, just what I would prefer 

3rd par. 
 and who has no digital data!? -> and who doesn't have digital data!?

5th par.
So go now, grasp a cup of coffee (or a hot chocolate), -> what about us tea lovers?

so far i like it.

**Comment by sils1297** [comment]
Hi,

This bugtracker is rather meant for coala issues, this tutorial is just a
thing that accidentally happens to be on this repository because I need
something where I can write markdown so I can copy the generated HTML to my
blog later. (Plus its versioned, so hey.)

Thanks for reading!
Am 25.02.2015 22:26 schrieb "sims1253" <notifications@github.com>:
