### ISSUE TITLE
Uninformative Error message when "gettext" is not installed.

### ISSUE THREAD

**Issue by shivanipoddariiith** [coala-analyzer/coala#368]
While running "./run_tests.py" after installing coala for the first time, I got this error message - 

![screen shot 2015-03-07 at 1 34 05 pm](https://cloud.githubusercontent.com/assets/2330579/6540645/90ad6ffa-c4cf-11e4-82db-9026501d3235.png)

The error message that is prompted assumes that the user already has "gettext" and "msgfmt" is not in the required path. The message should instead direct on installing gettext or correcting the path for magfmt.
Attaching a patch for the same.

**Comment by shivanipoddariiith** [comment]
#356  - Addresses this

**Comment by sils1297** [comment]
So, the message says we need msgfmt for compiling translations, which is exactly true. (So the user will probably get compiled translations in the end, I'm not sure if we do this right in our release distributions right now but I think we do.)

We use the gettext python library which is provided by default so if user has python he got it anyway.

So I'm assuming you want that message changed to make it clear that in order to get msgfmt on most distributions he has to install the gettext package?
