### ISSUE TITLE
Glob.py / _iter_or_combinations(): use regexes

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#404]
Because of their state-machine approach they are faster than checking each combination.
If regex expression shall not be supported it is possible to use `re.escape()` to escape the "or" strings so they are not treated with special chars (i.e. quantifiers etc.).

**Comment by sils1297** [comment]
probably doesn't make sense to do this until we support the recursion in regexes.

**Comment by sils1297** [comment]
blocked by #402

**Comment by Makman2** [comment]
Huh okay I thought I understand but I don't: You want to support recursive patterns?

**Comment by sils1297** [comment]
yes we want #402 for glob expression parsing. Or do you want to generate a regex out of the glob? Not so sure if we want that...

Tbh this isn't of much relevance to me because globbing works, is relatively well tested and we didn't have any issues with it. It's actually very similar to the implementation of `glob()` in the python libs IIRC.

**Comment by Makman2** [comment]
okay I misunderstood, I thought you wanted to support recursive regex patterns generally from the external `regex` module.

**Comment by smfn3321** [comment]
@Makman2 @sils1297 
To be honest I'm not even sure how much is to be gained from using regexes in globs, especially in _iter_or_combinations? 

I am not at all an expert for regexes, so please prove me wrong, but is there any tool in regexes that lets me expand the string/expression "a(b|c)(d|e)" into [""abd"", "abe", "acd", "ace"]? because that is pretty much what _iter_or_combinations does...


On a related note, do you think it would be possible to transform our glob expressions into regular expressions? That might be a lot faster indeed. One could try to parse the glob expression as a path as far as possible (i.e. /home/user/projects/coala_checked_project), do one os.walk() of that dir and yield all results that get matched by the regex.

My main Problem with that approach is, that I don't really want to check all files of the filesystem against the regex for obvious reasons. The current approach checks matching dirs only as far as needed, i.e. if the glob is "/home/user/(coala|baer)/*/*.py", the current approach iterates only one dir in /home, two dirs in /home/user/ which are then recursively checked but only for two levels. I hope you get what I mean? With a regex approach, one would probably have to check every file/dir in os.walk(/home/user/)?

**Comment by smfn3321** [comment]
fun fact: there are 42000 files on my system and it takes 24 seconds to os.walk() and count them :)

**Comment by sils1297** [comment]
Try cloc on them all :D I'm on Fabians side here currently. As I said I
dont see the real need for a change here and with the points given from
Fabian its at least doubt that there's a real win for us in there.
Am 25.03.2015 22:54 schrieb "Fabian Neuschmidt" <notifications@github.com>:

**Comment by Makman2** [comment]
Makes sense if you construct the file-tree out of the glob for each directory. Since using regexes in this case would nearly require the same amount of wrap-around and logic code this really makes no sense for now.

**Comment by smfn3321** [comment]
@Makman2 thank you for raising this issue and the discussion anyways.
@sils1297 feel free to close this issue.
