### ISSUE TITLE
various python related issues

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#407]
https://gist.githubusercontent.com/shivanipoddariiith/7f1f768d39d775864513/raw/8ded3c9940120559790dbddceef92c9203353519/gistfile1.txt

Valid concerns are raised here:

 * [x] `__del__` is not called deterministically across python implementations. It's hard to get hard info on that but that thing is unreliable at least if you change platforms/implementations. So we should not use it, he's right with that.
 * [x] he doesnt seem to like our naming scheme, maybe someone could investigate reasons?
 * [x] somehow it seems important that we inherit from object - investigation for reasons needed
 * [ ] I'd really appreciate an alternative to our test file usage because thats really awful and I never considered it good enough.

**Comment by Makman2** [comment]
- `__del__` makes sense when it's unpredictable.
- Naming scheme: We have one, changing it is just unneeded work. Some have their standards, we have ours^^ And to be honest: This example is in my opinion a no-go (if you even want to use it, use underscores):
  `somethingelsethathappenstohavemyclass.py`
- I think inheriting from `Object` is for backward compatibility, but not needed in Python >3 anymore.
- What do you mean with "test-file-usage"?

**Comment by sils1297** [comment]
test-file-usage: I mean our temporary files. We get the with mktemps or so which is awful.

**Comment by Makman2** [comment]
Yeah that is awful xD Streams are probably something better (like written in the link)

**Comment by smfn3321** [comment]
Well, I think part of the file problem (and the reason we went with tempfiles) is that we work a lot with (and therefore need to test) file access, collection, saving etc. One of the reasons coala doesn't run on pypy3 is, that sometimes somehow files that should be written to are empty afterwards. We simply rely on files in some cases. Note that we had succes in some cases with having permanent test files in a directory with our tests. I think this is the way to go because it is easier to understand, run, and modify.

**Comment by smfn3321** [comment]
Quoting PEP8 on the naming convention thing:

> Package and Module Names

Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

>Since module names are mapped to file names, and some file systems are case insensitive and truncate long names, it is important that module names be chosen to be fairly short -- this won't be a problem on Unix, but it may be a problem when the code is transported to older Mac or Windows versions, or DOS. 

Note that it is not necessarily my opinion that we should change things, the only valid point of the above is that windows is case insensitive. So it might not be wise to give names to modules that only differ in capitalization.

**Comment by sils1297** [comment]
are there any resources to the object inheritance? @Makman2 are you sure its only needed for backwards compatability?

**Comment by Makman2** [comment]
Okay I think I misunderstood myself a bit:
Python has two types of objects: The *old-style* and *new-style* objects. *Old-style* was the only possibility until python 2.2, where *new-style* classes were introduced. They have some new features (don't know actually what explicitly), but to use them you must derive explicitly from `object`. So every class that doesn't inherit something is *old-style*.
But this is a thing of the past since python 3. Every class is a *new-style* class, whether you derive from `object` or not. Some recommend anyway to subclass from `object`, but we target python 3 so no need for it^^

**Comment by sils1297** [comment]
@Makman2 ok let's trust on that :)

So what is the best way to go with the test files?

**Comment by Makman2** [comment]
(memory) streams maybe, but I don't know the infrastructure that good to know if this approach would work^^

**Comment by Makman2** [comment]
@sils1297 does this issue still apply? I would say fix on demand, we have the new `make_temp` macro which handles temp-file creation quite good imo, so we already made some steps into the right direction :)

**Comment by sils1297** [comment]
yeah most important points are adressed
