### ISSUE TITLE
Results need a range

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#739]
Results can currently only affect one line. However a bear might want to point to the exact char/range of chars where the problem is.

**Comment by sils1297** [comment]
actually implementing that in the result is easy, just add the member variables. Implementing it for the different output types is not.

**Comment by sils1297** [comment]
doing that on https://github.com/coala-analyzer/coala/pull/766

**Comment by sils1297** [comment]
TODO:

- [ ] Merge PatchResult into Result class
- [ ] Use SourcePosition in the Result class and adapt all usages
- [ ] Add column and end_line and end_column to SourcePosition

Removing easy because doing properly involves minor refactoring but it's certainly nothing to be afraid of.

**Comment by sils1297** [comment]
@fneu related bug: https://github.com/coala-analyzer/coala/issues/549

@fneu so we probably want to create a `SourceRange` object that holds two source positions and the result can then consist out of zero to several source range objects.

**Comment by fneu** [comment]
@sils1297 ok this is stupid. I'm sorry I tried but this get's much to complicated and I really don't see the sense in what I'm doing here, which makes it hard.

> "Add column and end_line and end_column to SourcePosition" 

I guess no because then we would have a range, but it's just supposed to give us a position? so just column then, right?

> "so we probably want to create a SourceRange object that holds two source positions and the result can then consist out of zero to several source range objects."

In my view this just adds complexity, since there is no point where we would use the SourcePosition besides the SourceRange? And the limits are very tight (same file, secons position after first) so I don't get at all why we need SourcePosition at all.

besides

what the heck do we need a SourceRange object for? just for sorting? why don't we just add the values to the result and sort by them by these attributes if we need to?

**Comment by fneu** [comment]
ok you cannot sort for a key that is None or int in different results to let's do this:
```
>>> class Result:
...     def __init__(self, file = "", start_line=-1, start_column = -1, end_line=-1, end_column = -1):
...         self.file = file
...         self.start_line = start_line
...         self.start_column = start_column
...         self.end_line = end_line
...         self.end_column = end_column
...     def __repr__(self):
...         return "{}:({},{})->({},{})".format(self.file, self.start_line, self.start_column, self.end_line, self.end_column)
... 
>>> results = (Result("A"), Result("B"), Result(), Result("A", 1, 1), Result("A", 2, 2, 3, 3), Result("A", 2, 2, 4, 4), Result("A", 2, 1, 8, 8))
>>> from operator import attrgetter
>>> sorted(results, key=attrgetter('file', 'start_line', 'start_column', 'end_line', 'end_column'))
[:(-1,-1)->(-1,-1), A:(-1,-1)->(-1,-1), A:(1,1)->(-1,-1), A:(2,1)->(8,8), A:(2,2)->(3,3), A:(2,2)->(4,4), B:(-1,-1)->(-1,-1)]
^no file            ^only file          ^file&line        ^start->end     ^later start    ^later end      ^next file
```

So, am I right that this would be a much simpler and leaner approach, with the only downside that we would have to take `''`amd `-1` as default values instead of `None`?

This would also mean no refactoring besides adding optional values for start and end.

Or is there some hidden merit to having classes for both?

**Comment by sils1297** [comment]
let's have a call at daytimes.

**Comment by sils1297** [comment]
Well, having an own position and a range object makes the design more reusable: e.g. if you write utility functions that search for something in a file, they might return a SourcePosition (e.g. a regex match might return a SourceRange without file set). So that was my thought behind this. apart from that it makes the sorting methods in the result simpler through moving out complexity. So that's at least my thoughts on that...

**Comment by Makman2** [comment]
This would maybe also useful for `StringProcessing`^^
