### ISSUE TITLE
directory restructurization

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#794]
hey, wouldn't it be better to move the bears into the coalib and have all test directories into one test directory in the root directory? Otherwise it's hard to find the tests...

**Comment by AbdealiJK** [comment]
What was the logic in keeping them as a separate directory ?
I assumed it was to decouple bears and coala

**Comment by sils1297** [comment]
correct.

2015-07-16 7:08 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Then personally I'd prefer not moving it into coalib.

If you think tests are difficult to find ... 2 things that can be done are :

1. In TestExecutor show <modulename>/<Testname>.py instead of jus ttestname.
2. merge `coalib/tests` and `bears/tests` into a folder `tests` which can
be put in the root of the repo

On Thu, Jul 16, 2015 at 10:49 AM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
hum, I'm probably creating problems where there aren't any...
