### ISSUE TITLE
glob/collecting: Accept strings too

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#824]
the methods there want a list but `glob("string")` makes sense too (and behaves very strangely), we should support that.

**Comment by AbdealiJK** [comment]
When I run `glob("coalib")` it accurately shows - `['coalib']`

What's weird about it ?

**Comment by sils1297** [comment]
at least I tried `collect_dirs("/some/absolute/path")` and got pretty weird resuilts, I may try reproducing later in a more organized way...

**Comment by sils1297** [comment]
so here's the issue:

```
>>> glob("*/pars*")
['coalib/parsing']
>>> collect_dirs("*/pars*")
['.misc', 'bears', 'docs', 'locale', 'coalib', '.git', '/']
```

**Comment by fneu** [comment]
@sils1297 well, yes, this kinda is by design. Glob always works on one file path and therefore takes a string. the collectors accept a list (iterable) of glob strings so that they only need to be called once.

Passing a string (iterable of chars) leads to glob being called on every char, in your example `glob('*')` yields the results you describe.

Anyway, we can change the design, so I will do that very quick.
