### ISSUE TITLE
JSON: make it async

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#830]
so on long term it would be nice if the JSON output would output log messages in realtime :)

**Comment by AbdealiJK** [comment]
Hmm, could you elaborate on real time ?

What can be done is send packets of json every X seconds or with every 100
results ... but I dont see how you can send half a json object

On Sun, Jul 19, 2015 at 11:45 PM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
I can think of just flushing out the initial `{"logs": [`, then flushing out log messages as soon as they arrive (locked so one at a time with no overlaps of course) and then the rest (results and so on) in the end

**Comment by AbdealiJK** [comment]
I see ... this is very complicated because we then need to write a custom
method to print jsons ... and cant use json.dumps

I think the better way for something like this is how pylint prints
messages. Make a "format-string" and keep printing output as and when it
comes (without any user input)

On Sun, Jul 19, 2015 at 11:54 PM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
thats a good idea
