### ISSUE TITLE
Printers: remove returns

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#833]
they make things complicated and tests hacky, use retrieve_stdout instead.

**Comment by AbdealiJK** [comment]
I'm using a variable to save the results because LogPrinter shouldn't need to test the stdout mechanisms of terminals (We found that apparently windows has some problem with printing COMPLEX_TEST_STRING)

ConsolePrinter should be looking at such things. Filed a bug for that at https://github.com/coala-analyzer/coala/issues/842
