### ISSUE TITLE
Use setuptools-version-command in rultor

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#837]
So, apparently, there is a better way of doing the whole version thing.

https://pypi.python.org/pypi/setuptools-version-command/2.1a1

It uses `git describe` to fetch the version from the closest tag.
As the rultor script merges the git locally before executing, the tag will get updated.

**Comment by sils1297** [comment]
I'm not fully bought on this, what are the advantages? I like the system we now have with rultor doing the version change automatically.

**Comment by AbdealiJK** [comment]
Currently, we've basically implemented exactly what the package does - I
thought it'd be better to use a package meant to do this

**Comment by sils1297** [comment]
what we have is a bit more flexible IMO because it checks for a valid version jump and allows us to not use tags. E.g. what we have on master is a development version from 0.1.1 alpha, `git describe` will however give you the 0.1.0 alpha tag because 0.1.1 was a bugfix release which had cherry picked important fix commits.

**Comment by AbdealiJK** [comment]
True. closing this.
