### ISSUE TITLE
Import classes into `__init__.py` directly

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#881]
Advantage:
Semantically it is better:
```python
from coalib.output.printers.Printer import Printer
```
better is:
```
from coalib.output.printers import Printer
```

Disadvantage:
Ambiguity - we can't use module instances any more, since the modules are called like the containing classes.
Solution to this problem: we could create other fields or only one dict-field `modules` that contains all loaded modules. I.e.:
`coalib.output.printers.module["Printer"]`

**Comment by sils1297** [comment]
we could rename our modules after some scheme and expose only public
classes in the init

2015-07-29 20:16 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
No time for this, accepting patches though.

**Comment by Makman2** [comment]
What means "no time for this"? why not just keeping the issue open?

**Comment by sils1297** [comment]
Because we need to focus on the more important tasks. Things that are out
of scope or we not important enough to be addressed with our limited
manpower... Well its actually better not to do them because there will
always be other things. This way people are invited to do PRs but we don't
stumble upon them when we manage bugs e.g. for releases and so on.
