### ISSUE TITLE
Export results to HTML

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#965]
It would be nice to generate a rather simple HTML page that can be pushed on some server :)

Supersedes https://github.com/coala-analyzer/coala/issues/459

**Comment by sils1297** [comment]
I'm currently looking towards creating a very simple page using https://pypi.python.org/pypi/html/1.16 and generate HTML of syntax highlighted code using https://pypi.python.org/pypi/Pygments/2.0.2

**Comment by sils1297** [comment]
Ok, html is unmaintained, https://pypi.python.org/pypi/ll-xist/5.13.1 seems to be actively developed.

**Comment by AbdealiJK** [comment]
Woah, let's not look for a python package. It's muuch simpler to let javascript do this.
[highlighting.js](https://highlightjs.org/) , [SHJS](shjs.sourceforge.net) , [etc](http://www.webdesignbooth.com/9-useful-javascript-syntax-highlighting-scripts/)
The javascript based libraries would be more maintained because they're just way more popular, and it makes sense to use a JS library as it's in a browser.

**Comment by sils1297** [comment]
@AbdealiJK good thought!

**Comment by AbdealiJK** [comment]
http://jshint.com/ uses code-mirror. I like their website, nice and simple + demonstrates the application well.

**Comment by AbdealiJK** [comment]
I believe this has moved to https://github.com/coala-analyzer/coala-html now ?

**Comment by sils1297** [comment]
indeed
